"""Execution policy and immutable, executable series locks for the RTG benchmark."""

from __future__ import annotations

import hashlib
import json
import platform
from dataclasses import dataclass
from importlib.metadata import version
from pathlib import Path

import torch
import yaml

from examples.pediatric_pneumonia._dataset_manifest import DatasetManifest
from examples.pediatric_pneumonia._protocol_lock import ProtocolLockError


@dataclass(frozen=True)
class ExecutionOptions:
    mode: str = "smoke"
    protocol_lock_path: Path | None = None
    resume: bool = False
    lost_work_seconds: float | None = None

    def __post_init__(self) -> None:
        if self.mode not in {"smoke", "pilot", "full"}:
            raise ValueError("mode must be smoke, pilot or full")
        if self.mode == "full" and self.protocol_lock_path is None:
            raise ProtocolLockError("full requires --protocol-lock; pilot never evaluates the test")
        if self.mode != "full" and self.protocol_lock_path is not None:
            raise ProtocolLockError("--protocol-lock is only used in full mode")
        if self.lost_work_seconds is not None and not self.resume:
            raise ValueError("--lost-work-seconds requires --resume")


def canonical_digest(payload: dict) -> str:
    return hashlib.sha256(
        json.dumps(payload, sort_keys=True, separators=(",", ":"), default=str).encode()
    ).hexdigest()


def execution_environment(device: torch.device) -> dict:
    root = Path(__file__).resolve().parents[2]
    source_files = [
        *root.joinpath("polyneat").rglob("*.py"),
        *root.joinpath("examples/pediatric_pneumonia").glob("*.py"),
        *root.joinpath("examples").glob("_*.py"),
        root / "pyproject.toml",
        root / "uv.lock",
    ]
    digest = hashlib.sha256()
    for path in sorted(source_files):
        digest.update(path.relative_to(root).as_posix().encode())
        digest.update(path.read_bytes().replace(b"\r\n", b"\n"))
    return {
        "python": platform.python_version(),
        "torch": str(torch.__version__),
        "dependencies": {
            name: version(name)
            for name in ("numpy", "scikit-learn", "Pillow", "torchvision", "PyYAML")
        },
        "cuda": torch.version.cuda,
        "device": str(device),
        "gpu": torch.cuda.get_device_name(device) if device.type == "cuda" else None,
        "precision": "float32",
        "deterministic_algorithms": torch.are_deterministic_algorithms_enabled(),
        "implementation_sha256": digest.hexdigest(),
    }


def read_execution_lock(path: Path) -> dict:
    payload = yaml.safe_load(path.read_text(encoding="utf-8"))
    if not isinstance(payload, dict) or payload.get("schema_version") != "2.0":
        raise ProtocolLockError("executable full runs require a v2 lock generated by freeze")
    recorded_digest = payload.pop("lock_sha256", None)
    if recorded_digest != canonical_digest(payload):
        raise ProtocolLockError("protocol lock changed after freezing; create a new study")
    return payload


def validate_execution_lock(
    path: Path,
    *,
    method: str,
    profile: dict,
    search_seed: int,
    device: torch.device,
    manifest: DatasetManifest | None = None,
) -> str:
    """Verify actual configuration, seed, environment and (when audited) data."""
    payload = read_execution_lock(path)
    if payload["profiles"].get(method) != profile:
        raise ProtocolLockError(f"{method}: actual profile differs from the frozen profile")
    if search_seed not in payload["search_seeds"]:
        raise ProtocolLockError("search seed was not declared in the frozen series")
    if payload["environment"] != execution_environment(device):
        raise ProtocolLockError("execution environment differs from the frozen series")
    locked_manifest, digest = DatasetManifest.read_json_file(path.parent / payload["manifest_path"])
    if digest != payload["manifest_sha256"] or locked_manifest.blocking_findings:
        raise ProtocolLockError("locked manifest differs or contains blocking audit findings")
    if manifest is not None and manifest.compute_sha256() != digest:
        raise ProtocolLockError("current archive/split differs from the frozen manifest")
    return canonical_digest(payload)
